Assistant.create(name: "Prof Sonia", password: "iluvpokeresearch!" )
Assistant.create(name: "Hop", password: "leonchampbro")
Assistant.create(name: "Jacques", password: "pokeresearchnewbie")
Assistant.create(name: "Barry", password: "tattiebobattie")

Pokemon.create(species: "Pikachu", type1: "Electric", type2: "None")
Pokemon.create(species: "Grookey", type1: "Grass", type2: "None" )
Pokemon.create(species: "Rotom", type1: "Ghost", type2: "Electric" )
Pokemon.create(species: "Flapple", type1: "Grass", type2: "Dragon")
Pokemon.create(species: "Sableye", type1: "Ghost", type2: "Dark")

Entry.create(content: "It ate a sour apple, and that induced its evolution. In its cheeks, it stores an acid capable of causing chemical burns.", assistant_id: 1, pokemon_id: 4)
Entry.create(content: "When it uses its special stick to strike up a beat, the sound waves produced carry revitalizing energy to the plants and flowers in the area.", assistant_id: 4, pokemon_id: 2)
Entry.create(content: "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.", assistant_id: 1, pokemon_id: 1)
Entry.create(content: "It attacks with rapid beats of its stick. As it strikes with amazing speed, it gets more and more pumped.", assistant_id: 2, pokemon_id: 2)
Entry.create(content: "Under the influence of Gigantamax energy, it produces much more sweet nectar, and its shape has changed to resemble a giant apple.", assistant_id: 3, pokemon_id: 4)
Entry.create(content: "One boy's invention led to the development of many different machines that take advantage of Rotom's unique capabilities.", assistant_id: 1, pokemon_id: 3)
Entry.create(content: "When Pikachu meet, they'll touch their tails together and exchange electricity through them as a form of greeting.", assistant_id: 2, pokemon_id: 1)
Entry.create(content: "It flies on wings of apple skin and spits a powerful acid. It can also change its shape into that of an apple", assistant_id: 3, pokemon_id: 4)
Entry.create(content: "This Pokémon is feared. When its gemstone eyes begin to glow with a sinister shine, it's believed that Sableye will steal people's spirits away.", assistant_id: 4, pokemon_id: 5)